### ISSUE TITLE
Even handler leak

### ISSUE THREAD

**Issue by kzaher** [MetaMask/logo#19] opened 2019-02-03 17:34 UTC
It seems to me that this component is leaking event handlers.

https://github.com/MetaMask/metamask-logo/blob/gh-pages/index.js#L261

I would suggest adding an API that would allow explicit registration/disposal of those event handlers. I can add it if you like.

**Comment by kumavis** [comment] 2021-03-31 13:21
yes you're correct
closing as duplicate of https://github.com/MetaMask/logo/issues/23

**Closed by kumavis** 2021-03-31 13:21 UTC
